def generate_markdown(state):
    """
    Compiles the research state into a Markdown report.
    Supports both old state format (topic, context, reasoning_trace) 
    and new format (messages, research_data).
    """
    # Handle different state formats
    topic = state.get("topic", "")
    if not topic and "messages" in state:
        # Extract from messages if available
        messages = state.get("messages", [])
        if messages:
            topic = messages[0].content if hasattr(messages[0], 'content') else str(messages[0])
    
    hypothesis = state.get("hypothesis", "No Hypothesis Generated")
    reasoning = state.get("reasoning_trace", "")
    
    # Handle context/research_data
    context = state.get("context", [])
    research_data = state.get("research_data", "")
    if research_data and not context:
        context = [research_data]
    
    feedback = state.get("feedback", state.get("critique_feedback", "No Feedback"))
    
    # Format Context
    context_section = ""
    if isinstance(context, list):
        for item in context:
            context_section += f"{item}\n\n"
    else:
        context_section = str(context)
        
    report = f"""# Research Report: {topic}

## Abstract
{hypothesis[:200] if len(hypothesis) > 200 else hypothesis}...

## 1. Introduction & Context
The following literature was surveyed to understand the landscape of **{topic}**:

{context_section}

## 2. Reasoning Process
{"The following logical path was taken to arrive at the hypothesis:" if reasoning else "Reasoning process integrated into hypothesis generation."}

{f"> {reasoning.replace(chr(10), chr(10)+"> ")}" if reasoning else ""}

## 3. Proposed Hypothesis
{hypothesis}

## 4. Discussion & Critique (Reviewer #2)
The following potential flaws were identified:

{feedback}

---
*Report generated by Agentic Research Assistant v0.1*
"""
    return report

def save_report(report_content, filename="output.md"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_content)
    print(f"Report saved to {filename}")
